document.addEventListener('DOMContentLoaded', () => {
    const stack = document.getElementById('cards-stack');
    const btnNope = document.getElementById('btn-nope');
    const btnLike = document.getElementById('btn-like');
    const btnReload = document.getElementById('btn-reload');
    
    // Marketing UI Elements
    const bgBlurImg = document.getElementById('bg-blur-img');
    const titleEl = document.getElementById('movie-title');
    const yearEl = document.getElementById('movie-year');
    const runtimeEl = document.getElementById('movie-runtime');
    const genreEl = document.getElementById('movie-genre');
    const descEl = document.getElementById('movie-desc');

    let movies = [];
    const WHATSAPP_NUM = "201124428203";
    
    // Session-based memory for liked movies - CLEAR ON EACH REFRESH as requested
    sessionStorage.removeItem('likedMovies');
    let likedMovies = [];
    
    function updateCartUI() {
        const cartCount = document.getElementById('cart-count');
        if (cartCount) {
            cartCount.innerText = likedMovies.length;
            cartCount.style.display = likedMovies.length > 0 ? 'inline-block' : 'none';
            
            // Trigger Pop Animation
            cartCount.classList.remove('pop');
            void cartCount.offsetWidth; // trigger reflow
            cartCount.classList.add('pop');
            setTimeout(() => cartCount.classList.remove('pop'), 300);
        }
    }
    
    function addToLiked(movieTitle) {
        if (!likedMovies.includes(movieTitle)) {
            likedMovies.push(movieTitle);
            sessionStorage.setItem('likedMovies', JSON.stringify(likedMovies));
            updateCartUI();
        }
    }
    
    async function loadMovies() {
        try {
            titleEl.innerHTML = "LOADING...";
            movies = window.moviesData || [];
            
            if (movies.length === 0) {
                throw new Error("No data found in window.moviesData");
            }
            
            movies.sort(() => Math.random() - 0.5);
            renderCards();
        } catch (err) {
            console.error(err);
            titleEl.innerHTML = "ERROR LOADING";
            descEl.innerHTML = "Ensure movies.js is generated by the python script and loaded correctly.";
        }
    }

    function renderCards() {
        stack.innerHTML = '';
        
        if (!movies || movies.length === 0) return;

        // Render backwards for z-index stacking
        for (let i = movies.length - 1; i >= 0; i--) {
            const movie = movies[i];
            const card = document.createElement('div');
            card.className = 'movie-card';
            card.dataset.index = i;
            
            // Graceful path handling (especially if json is stale)
            let posterPath = movie.poster;
            if(!posterPath || posterPath.includes('placeholder.jpg')) {
                posterPath = 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80';
            } else {
                // Ensure correct relative path depending on where script is running
                posterPath = posterPath.replace(/\\/g, '/');
            }
            
            card.style.backgroundImage = `url('${posterPath}')`;
            
            card.innerHTML = `
                <div class="absolute inset-0 bg-gradient-to-t from-background via-background/20 to-transparent pointer-events-none"></div>
                <div class="badge like">LIKE</div>
                <div class="badge nope">NOPE</div>
            `;
            
            stack.appendChild(card);
        }

        initCards();
    }

    function updateMarketingPanel(movie) {
        if(!movie) {
            // Looping: If no more movies, restart from beginning
            renderCards();
            return;
        }
        
        // Display title cleanly - no automatic & insertion
        titleEl.innerHTML = movie.title;
        
        yearEl.innerText = movie.year || "2024";
        runtimeEl.innerText = movie.runtime || "120 MIN";
        genreEl.innerText = movie.genre || "CINEMA";
        descEl.innerText = movie.desc || "No description provided.";
        
        const topCard = document.querySelector('.movie-card:not(.removed)');
        if(topCard && bgBlurImg) {
            let imgUrl = topCard.style.backgroundImage.slice(5, -2).replace(/"/g, "");
            bgBlurImg.src = imgUrl;
        }
    }

    function initCards() {
        const remaining = document.querySelectorAll('.movie-card:not(.removed)');
        
        if (remaining.length === 0) {
            updateMarketingPanel(null);
            return;
        }

        const topIndex = remaining[0].dataset.index;
        updateMarketingPanel(movies[topIndex]);

        remaining.forEach((card, index) => {
            card.onmousedown = null;
            card.ontouchstart = null;
            
            card.style.zIndex = remaining.length - index;
            card.style.transition = 'transform 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275), opacity 0.5s ease, filter 0.5s ease';
            
            if(index === 0) {
                 card.style.transform = `translate(0px, 0px) scale(1) rotate(2deg)`;    
                 card.style.filter = 'brightness(1)';
                 card.style.opacity = 1;
            } else if (index === 1) {
                 card.style.transform = `translate(15px, 20px) scale(0.95) rotate(-1deg)`;
                 card.style.filter = 'brightness(0.6)';
                 card.style.opacity = 0.9;
            } else if (index === 2) {
                 card.style.transform = `translate(30px, 40px) scale(0.9) rotate(1deg)`;
                 card.style.filter = 'brightness(0.3)';
                 card.style.opacity = 0.7;
            } else {
                 card.style.transform = `translate(0px, 60px) scale(0.85)`;
                 card.style.opacity = 0;
            }
        });

        setupSwipe(remaining[0]);
        
        // Add wiggle hint if it's the first card and no interaction yet
        if (remaining.length === movies.length) {
            remaining[0].classList.add('hint-wiggle');
        }
    }
    
    function hideTutorial() {
        const topCard = document.querySelector('.movie-card:not(.removed)');
        if (topCard) topCard.classList.remove('hint-wiggle');
        
        document.getElementById('tutorial-left')?.style.setProperty('opacity', '0');
        document.getElementById('tutorial-right')?.style.setProperty('opacity', '0');
        setTimeout(() => {
            document.getElementById('tutorial-left')?.remove();
            document.getElementById('tutorial-right')?.remove();
        }, 500);
    }

    let currentY = 0; // scoped broadly for swipe function reference

    function setupSwipe(card) {
        let isDragging = false;
        let startX = 0, startY = 0, currentX = 0;
        currentY = 0;
        
        const badgeLike = card.querySelector('.badge.like');
        const badgeNope = card.querySelector('.badge.nope');

        const onTouchStart = (e) => {
            if(e.target.closest('button')) return;
            isDragging = true;
            startX = e.type.includes('mouse') ? e.clientX : e.touches[0].clientX;
            startY = e.type.includes('mouse') ? e.clientY : e.touches[0].clientY;
            card.classList.add('moving');
            hideTutorial(); // Remove hints as soon as user touches
        };

        const onTouchMove = (e) => {
            if (!isDragging) return;
            
            const x = e.type.includes('mouse') ? e.clientX : e.touches[0].clientX;
            const y = e.type.includes('mouse') ? e.clientY : e.touches[0].clientY;
            
            currentX = x - startX;
            currentY = y - startY;

            // Only prevent default if swiping horizontally
            if (Math.abs(currentX) > Math.abs(currentY) || Math.abs(currentX) > 10) {
                if (e.cancelable) e.preventDefault();
            } else {
                // If moving vertically, stop dragging to allow scroll
                isDragging = false;
                card.classList.remove('moving');
                return;
            }

            const rotate = 2 + (currentX * 0.05);
            card.style.transform = `translate(${currentX}px, ${currentY}px) rotate(${rotate}deg)`;

            if (currentX > 0) {
                badgeLike.style.opacity = Math.min(currentX / 100, 1);
                badgeNope.style.opacity = 0;
            } else {
                badgeNope.style.opacity = Math.min(Math.abs(currentX) / 100, 1);
                badgeLike.style.opacity = 0;
            }
        };

        const onTouchEnd = () => {
            if(!isDragging) return;
            isDragging = false;
            card.classList.remove('moving');

            const threshold = window.innerWidth / 4 > 100 ? window.innerWidth / 4 : 100;

            if (currentX > threshold) {
                swipe(card, 1);
            } else if (currentX < -threshold) {
                swipe(card, -1);
            } else {
                card.style.transform = 'translate(0px, 0px) scale(1) rotate(2deg)';
                badgeLike.style.opacity = 0;
                badgeNope.style.opacity = 0;
            }
            currentX = 0;
            currentY = 0;
        };

        card.onmousedown = onTouchStart;
        card.ontouchstart = onTouchStart;
        window.onmousemove = onTouchMove;
        window.ontouchmove = onTouchMove;
        window.onmouseup = onTouchEnd;
        window.ontouchend = onTouchEnd;
    }

    function swipe(card, dir) {
        window.onmousemove = null;
        window.ontouchmove = null;
        window.onmouseup = null;
        window.ontouchend = null;

        const endX = Math.max(window.innerWidth, 1000) * dir; 
        card.style.transform = `translate(${endX}px, ${currentY || 50}px) rotate(${dir * 30}deg)`;
        card.classList.add('removed');
        card.style.opacity = 0;
        
        setTimeout(() => {
            card.remove();
            if (dir === 1) {
                const movie = movies[card.dataset.index];
                addToLiked(movie.title);
            }
            initCards();
        }, 350);
    }

    btnNope?.addEventListener('click', () => {
        const topCard = document.querySelector('.movie-card:not(.removed)');
        if(topCard) swipe(topCard, -1);
    });

    btnLike?.addEventListener('click', () => {
        const topCard = document.querySelector('.movie-card:not(.removed)');
        if(topCard) swipe(topCard, 1);
    });
    
    // WhatsApp integration
    function handlePurchase(actionType) {
        const topCard = document.querySelector('.movie-card:not(.removed)');
        let currentMovieTitle = "";
        
        if (topCard) {
            currentMovieTitle = movies[topCard.dataset.index].title;
            addToLiked(currentMovieTitle); // Add current one to list too
        }

        const now = new Date();
        const hour = now.getHours();
        const greeting = (hour >= 5 && hour < 12) ? "صباح الفل" : "مساء الفل";

        // Smart Genre Analysis
        const likedGenres = likedMovies.map(title => movies.find(m => m.title === title)?.genre || "");
        const uniqueGenres = [...new Set(likedGenres.filter(g => g))].join(' و');

        const moviesList = likedMovies.join('، \u200F');
        let msgText = `\u200Fيا ${greeting}، كنت بتفرج على موقع Noir Auteur والحقيقة الأفلام ذوقها عالي جداً. `;
        
        if (likedMovies.length === 1) {
            msgText += `\u200Fاستقريت فعلاً على فيلم (${likedMovies[0]}) ومحتاج أطلبه. `;
        } else if (likedMovies.length > 1) {
            msgText += `\u200Fاستقريت فعلاً على مجموعة أفلام من ذوقي (خاصة أفلام ${uniqueGenres}) ومحتاج أطلبهم: (${moviesList}). `;
        }
        
        msgText += `\u200Fلو سمحت محتاج أعرف تفاصيل الشراء لأعلى جودة متوفرة، الحساب كدا يبقى كام وإيه نظام التسليم؟ تسلم مقدماً.`;
        
        const msg = encodeURIComponent(msgText);
        window.open(`https://wa.me/${WHATSAPP_NUM}?text=${msg}`, '_blank');
    }

    // Top Header Buy Button
    document.querySelector('header #btn-buy')?.addEventListener('click', () => handlePurchase('buy'));
    
    // Panel Buy Button (if any) or shared panel buttons
    document.getElementById('btn-buy')?.addEventListener('click', () => handlePurchase('buy'));
    document.getElementById('btn-book')?.addEventListener('click', () => handlePurchase('book'));
    
    // Shopping bag click should also trigger purchase flow with the list
    document.getElementById('btn-whatsapp-bag')?.addEventListener('click', (e) => {
        e.preventDefault();
        handlePurchase('bag');
    });
    
    // Mobile ticket window click
    document.getElementById('btn-ticket-window')?.addEventListener('click', (e) => {
        e.preventDefault();
        handlePurchase('tickets');
    });

    btnReload?.addEventListener('click', () => {
        loadMovies();
    });

    updateCartUI();
    loadMovies();
});
