const admin = require('firebase-admin');
const nodemailer = require('nodemailer');

// 1. Initialize Firebase Admin using Service Account from Environment
const serviceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

async function sendWeeklyReport() {
    console.log('📊 Fetching data from Firestore...');
    
    // Calculate last 7 days
    const oneWeekAgo = new Date();
    oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);

    try {
        const snapshot = await db.collection('events')
            .where('timestamp', '>=', oneWeekAgo)
            .get();

        const events = [];
        snapshot.forEach(doc => events.push(doc.data()));

        if (events.length === 0) {
            console.log('⚠️ No events found for the last 7 days. Skipping report.');
            return;
        }

        // --- Aggregation Logic ---
        const uniqueSessions = new Set(events.map(e => e.session_id)).size;
        const purchases = events.filter(e => e.event_type === 'purchase').length;
        const likes = events.filter(e => e.event_type === 'like').length;
        const nopes = events.filter(e => e.event_type === 'nope').length;
        const conversionRate = uniqueSessions > 0 ? ((purchases / uniqueSessions) * 100).toFixed(2) : 0;

        const movieLikes = {};
        events.filter(e => e.event_type === 'like').forEach(e => {
            const title = e.metadata?.movie || 'Unknown';
            movieLikes[title] = (movieLikes[title] || 0) + 1;
        });
        const topMovies = Object.entries(movieLikes)
            .sort((a, b) => b[1] - a[1])
            .slice(0, 5);

        // --- Email Construction ---
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST || 'smtp.gmail.com',
            port: 587,
            secure: false,
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS,
            },
        });

        const movieRows = topMovies.map(([title, count]) => `
            <tr>
                <td style="padding: 10px; border-bottom: 1px solid #333;">${title}</td>
                <td style="padding: 10px; border-bottom: 1px solid #333; text-align: right; color: #f2ca50;">${count} Likes</td>
            </tr>
        `).join('');

        const htmlContent = `
            <div style="font-family: sans-serif; max-width: 600px; margin: auto; background: #000; color: #fff; padding: 30px; border-radius: 15px; border: 1px solid #f2ca50;">
                <h1 style="color: #f2ca50; text-align: center; border-bottom: 1px solid #f2ca50; padding-bottom: 10px;">Noir Auteur Cloud Report</h1>
                <p style="text-align: center; color: #888;">Weekly Analytics Summary (Auto-Generated)</p>
                
                <div style="display: flex; justify-content: space-around; margin: 20px 0;">
                    <div style="text-align: center; background: #111; padding: 15px; border-radius: 10px; width: 45%;">
                        <div style="font-size: 24px; color: #f2ca50; font-weight: bold;">${uniqueSessions}</div>
                        <div style="font-size: 10px; text-transform: uppercase;">Unique Visitors</div>
                    </div>
                    <div style="text-align: center; background: #111; padding: 15px; border-radius: 10px; width: 45%;">
                        <div style="font-size: 24px; color: #10b981; font-weight: bold;">${conversionRate}%</div>
                        <div style="font-size: 10px; text-transform: uppercase;">Conversion Rate</div>
                    </div>
                </div>

                <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                    <tr style="background: #111; color: #f2ca50;">
                        <th style="padding: 10px; text-align: left;">Top Movies</th>
                        <th style="padding: 10px; text-align: right;">Count</th>
                    </tr>
                    ${movieRows}
                </table>

                <div style="margin-top: 30px; padding-top: 10px; border-top: 1px solid #333; font-size: 12px; color: #555; text-align: center;">
                    This report was generated by GitHub Actions. No server maintenance required.
                </div>
            </div>
        `;

        await transporter.sendMail({
            from: `"Noir Analytics Hub" <${process.env.SMTP_USER}>`,
            to: process.env.REPORT_RECIPIENT_EMAIL,
            subject: `📊 Noir Auteur: Weekly Insights (${new Date().toLocaleDateString()})`,
            html: htmlContent,
        });

        console.log('✅ Cloud Report sent successfully!');
    } catch (error) {
        console.error('❌ Error generating report:', error);
        process.exit(1);
    }
}

sendWeeklyReport();
